variables:
    NODE_VERSION: "alpine3.12"

stages:
    - build
    - test
    - deploy

build:
    stage: build
    image: node:${NODE_VERSION}
    script:
        - yarn lint
        - yarn build
        - yarn docs
    artifacts:
        expire_in: 1 day
        paths:
            - packages/core/dist/
            - packages/resolver/dist/
            - packages/manager/dist/
            - packages/taquito/dist/
            - packages/taquito-client/dist/
            - packages/conseil-client/dist/
            - dist/typedoc
    tags:
        - docker

test:core:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/core test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/core/coverage/
        reports:
            junit:
                - ./packages/core/coverage/junit.xml
    tags:
        - docker

test:resolver:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/resolver test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/resolver/coverage/
        reports:
            junit:
                - ./packages/resolver/coverage/junit.xml
    tags:
        - docker

test:manager:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/manager test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/manager/coverage/
        reports:
            junit:
                - ./packages/manager/coverage/junit.xml
    tags:
        - docker

test:taquito:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/taquito test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/taquito/coverage/
        reports:
            junit:
                - ./packages/taquito/coverage/junit.xml
    tags:
        - docker

test:taquito-client:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/taquito-client test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/taquito-client/coverage/
        reports:
            junit:
                - ./packages/taquito-client/coverage/junit.xml
    tags:
        - docker

test:conseil-client:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/conseil-client test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/conseil-client/coverage/
        reports:
            junit:
                - ./packages/conseil-client/coverage/junit.xml
    tags:
        - docker

test:integration:florencenet:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - TD_NETWORK=florencenet TD_RPC_URL=${RPC_URL_FLORENCENET} yarn integration-test
    tags:
        - docker

test:integration:granadanet:
    stage: test
    image: node:${NODE_VERSION}
    allow_failure: false
    script:
        - TD_NETWORK=granadanet TD_RPC_URL=${RPC_URL_GRANADANET} yarn integration-test
    tags:
        - docker

deploy_typedoc:
    stage: deploy
    image: microsoft/azure-cli
    dependencies:
        - build
    script:
        - az storage blob delete-batch -s "\$web" --connection-string "DefaultEndpointsProtocol=https;AccountName=tdclienttypedoc;AccountKey=${AZURE_STORAGE_CONNECTION_STRING_ACCOUNTKEY_CLIENT_DOCS};EndpointSuffix=core.windows.net"
        - az storage blob upload-batch -d "\$web" -s dist/typedoc --connection-string "DefaultEndpointsProtocol=https;AccountName=tdclienttypedoc;AccountKey=${AZURE_STORAGE_CONNECTION_STRING_ACCOUNTKEY_CLIENT_DOCS};EndpointSuffix=core.windows.net"
    only:
        - tags