stages:
    - build
    - test

build:
    stage: build
    image: node:alpine3.12
    script:
        - yarn lint
        - yarn build
        - yarn docs
    artifacts:
        expire_in: 1 day
        paths:
            - packages/core/dist/
            - packages/resolver/dist/
            - packages/manager/dist/
            - packages/client/dist/
            - dist/typedoc
    tags:
        - docker

test:core:
    stage: test
    image: node:alpine3.12
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/core test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/core/coverage/
        reports:
            junit:
                - ./packages/core/coverage/junit.xml
    tags:
        - docker

test:resolver:
    stage: test
    image: node:alpine3.12
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/resolver test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/resolver/coverage/
        reports:
            junit:
                - ./packages/resolver/coverage/junit.xml
    tags:
        - docker

test:manager:
    stage: test
    image: node:alpine3.12
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/manager test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/manager/coverage/
        reports:
            junit:
                - ./packages/manager/coverage/junit.xml
    tags:
        - docker

test:client:
    stage: test
    image: node:alpine3.12
    allow_failure: false
    script:
        - yarn workspace @tezos-domains/client test
    coverage: /All files[^|]*\|[^|]*\s+([\d\.]+)/
    artifacts:
        paths:
            - packages/client/coverage/
        reports:
            junit:
                - ./packages/client/coverage/junit.xml
    tags:
        - docker

# test:integration:carthagenet:
#     stage: test
#     image: node:alpine3.12
#     allow_failure: false
#     script:
#         - TD_NETWORK=carthagenet TD_RPC_URL=${RPC_URL_CARTHAGENET} yarn workspace integration-tests integration-test
#     tags:
#         - docker

test:integration:delphinet:
    stage: test
    image: node:alpine3.12
    allow_failure: false
    script:
        - TD_NETWORK=delphinet TD_RPC_URL=${RPC_URL_DELPHINET} yarn workspace integration-tests integration-test
    tags:
        - docker