export const BuiltInAddresses = {
    mainnet: {
        'nameRegistry': { address: 'TODO', resolveProxyContract: true },
        'nameRegistry:set_child_record': { address: 'TODO' },
        'nameRegistry:update_record': { address: 'TODO' },
        'nameRegistry:claim_reverse_record': { address: 'TODO' },
        'nameRegistry:update_reverse_record': { address: 'TODO' },
        'tldRegistrar:tez': { address: 'TODO', resolveProxyContract: true },
        'tldRegistrar:tez:commit': { address: 'TODO' },
        'tldRegistrar:tez:buy': { address: 'TODO' },
        'tldRegistrar:tez:renew': { address: 'TODO' },
    },
    carthagenet: {
        'nameRegistry': { address: 'KT1Ta1wDxDZJVhZzZSw8D6D5LahJZgPtmvx1', resolveProxyContract: true },
        'nameRegistry:set_child_record': { address: 'KT1XjDmgH7jSVSGLzUQSdC89LQ8Ho3Wn6S8w' },
        'nameRegistry:update_record': { address: 'KT1W3vXaMefoPqBSPfd7oKZhmrANGMk3zVzy' },
        'nameRegistry:claim_reverse_record': { address: 'KT1S7ZkEiYp51EgUautKi4JWpp9M7RSiZcsE' },
        'nameRegistry:update_reverse_record': { address: 'KT1NDCo9iZe4qDcb85YHe3QYKsRNpCDUvUMC' },
        'tldRegistrar:tez': { address: 'KT1LsXBWBBtZeotX5FYH1RBpRLjLhyJGpUNx', resolveProxyContract: true },
        'tldRegistrar:tez:commit': { address: 'KT1LsXBWBBtZeotX5FYH1RBpRLjLhyJGpUNx' },
        'tldRegistrar:tez:buy': { address: 'KT1FMVfxxaQMnvc32pCLzUf3UoezXMPsr72g' },
        'tldRegistrar:tez:renew': { address: 'KT18zwTExt8kMvb8Ar49VbZ2BJhdha75deSx' },
    },
    custom: null,
};
